FROM ubuntu:focal

# Install dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update
RUN apt-get -y install \
    git cmake build-essential \
    libusb-1.0-0-dev 

# Install libch340
RUN git clone https://github.com/seanavery/lib-ch340.git && \
    cd lib-ch340 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install
