name: Test Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install git cmake build-essential libusb-1.0-0-dev

    - name: Build library
      run: make build
